name: habitt_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  fluttertoast: ^9.0.0
  http: ^1.5.0
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  awesome_notifications: ^0.10.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4   # ✅ keep it here in dev_dependencies

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png   # ✅ make sure the file exists here

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#2196F3"          # Background color
  image: assets/icon/splash.png  # Your splash image/logo
  android: true
  ios: false
